version: "3.9"

services:
  locust:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    env_file: 
      - ./.env
    volumes:
      - ./locustfile.py:/app/locustfile.py
