version: "3.9"

volumes:
  mongo-data:

services:
  mongo:
    image: mongo:3.6.2-jessie
    ports:
      - 27015:27015
    volumes:
      - mongo-data:/data/db

  gamification-engine:
    build:
      context: ../
      dockerfile: docker/engine/Dockerfile
    ports:
      - "8010:8010"
      - "7777:7777"
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    env_file: 
      - ./engine/gamification.env
    volumes:
      - ./engine/logs:/app/game-engine.web/logs
      - ./engine/config:/app/config

  setup-gamification-engine:
    build:
      context: ../
      dockerfile: docker/setup_gamification_engine/Dockerfile
    depends_on:
      - gamification-engine
    links:
      - gamification-engine:gamification-engine
    env_file: 
      - ./.env
    profiles:
      - setup
    volumes:
      - ./setup_gamification_engine/main.py:/app/main.py

  web:
    build:
      context: ../
      dockerfile: docker/web/Dockerfile
    command: node server.js
    env_file: 
      - ./.env
    volumes:
      - ./volumes/databases:/app/databases
      - ./volumes/pbfFiles:/app/pbfFiles

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./volumes/pbfFiles:/mnt/volumes/pbfFiles
      - ./web/auth0-conf.js:/usr/share/nginx/html/auth0-conf.js
  setup_web:
    profiles:
      - setup
    command: /data/Trento.xml
    build:
      context: ../
      dockerfile: docker/setup_web/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./setup_web/main.py:/app/main.py
      - ./setup_web/bikingimprover:/app/bikingimprover
      - ./setup_web/data:/data
      - ./volumes/pbfFiles:/app/out/pbfFiles
      - ./volumes/databases:/app/out/databases
